# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: schemas/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: make-doc
        name: make-doc
        entry: python doc/make.py
        language: python
        types: [python]
        additional_dependencies: [json-schema-for-humans]
        pass_filenames: false
